# Generated by Django 5.0.4 on 2025-08-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atelier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('is_default', models.BooleanField(default=False, verbose_name='Статус по умолчанию')),
            ],
            options={
                'verbose_name': 'Статус заказа',
                'verbose_name_plural': 'Статусы заказов',
            },
        ),
        migrations.CreateModel(
            name='PlannerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_day', models.PositiveIntegerField(default=8, verbose_name='Рабочих часов в день')),
                ('work_days', models.CharField(default='1,2,3,4,5', help_text='Через запятую, где 1 - понедельник, 7 - воскресенье', max_length=13, verbose_name='Рабочие дни (1-ПН,7-ВС)')),
            ],
            options={
                'verbose_name': 'Настройка планера',
                'verbose_name_plural': 'Настройки планера',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='Цвет в планере'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Планируемая дата'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_hours',
            field=models.PositiveIntegerField(default=1, verbose_name='Планируемые часы'),
        ),
        migrations.AddField(
            model_name='order',
            name='planned_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='atelier.orderstatus', verbose_name='Статус'),
        ),
    ]
